# -*- mode: ruby -*-
# vim: set ft=ruby :

$script = <<-SCRIPT
mkdir -p ~root/.ssh
cp ~vagrant/.ssh/auth* ~root/.ssh
yum install -y mdadm smartmontools hdparm gdisk
SCRIPT

MACHINES = {
  :myclone => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.101',
    :disks => {
      :sata1 => {
        :dfile => './sata1.vdi',
        :size => 5120,
        :port => 1
      },
      :sata2 => {
        :dfile => './sata2.vdi',
        :size => 5120,
        :port => 2
      }
    }
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    config.vm.synced_folder '.', '/vagrant', disabled: true

    config.vm.define boxname do |box|

      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s

      #box.vbguest.auto_update = false
      box.vm.box_check_update = false
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      
      box.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        needsController = false

        boxconfig[:disks].each do |dname, dconf|
          unless File.exist?(dconf[:dfile])
            vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
            needsController = true
          end

        end
      if needsController == true
        vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
        boxconfig[:disks].each do |dname, dconf|
          vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
        end
    end
  end
  box.vm.provision "shell", inline: $script

end
end
end
