---
# handlers file for roles/nginx
  - name: start nginx
    systemd:
      name: nginx
      enabled: yes
      state: restarted
      masked: no

  - name: reload nginx
    systemd:
      name: nginx
      state: reloaded
