---
# tasks file for roles/nginx-ha

- name: get wget
  yum: name=wget state=present

- name: install epel repo
  yum: name=epel-release state=present

- name: install nginx repo
  blockinfile:
    path: /etc/yum.repos.d/nginx.repo
    block: |
      [nginx-stable]
      name=nginx stable repo
      baseurl=http://nginx.org/packages/centos/$releasever/$basearch/
      gpgcheck=1
      enabled=1
      gpgkey=https://nginx.org/keys/nginx_signing.key
      module_hotfixes=true

      [nginx-mainline]
      name=nginx mainline repo
      baseurl=http://nginx.org/packages/mainline/centos/$releasever/$basearch/
      gpgcheck=1
      enabled=0
      gpgkey=https://nginx.org/keys/nginx_signing.key
      module_hotfixes=true
    create: yes

- name: install elastic repo
  include_role:
    name: common
    tasks_from: repo_elastic.yml

- name: install filebeat
  yum: name=filebeat state=present

- name: configure filebeat
  copy:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: start filebeat
  systemd: name=filebeat state=started enabled=yes

- name: include tasks for keepalived
  include_role:
    name: common
    tasks_from: setup_keepalived.yml

- name: install nginx
  yum: name=nginx state=latest

- name: update selinux policies
  yum:
    name:
      - selinux-policy
      - selinux-policy-targeted
    state: latest

- name: setup selinux for nginx
  command: setsebool -P httpd_can_network_connect 1

- name: create nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/mattermost

- name: setup nginx config
  shell: |
    rm /etc/nginx/conf.d/default.conf
    ln -s /etc/nginx/conf.d/mattermost /etc/nginx/conf.d/default.conf
    chown nginx.nginx /var/cache/nginx/ -R

- name: create keepalived config
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  vars:
    state: MASTER
    priority: 100
  when: inventory_hostname == "ngx1"

- name: create keepalived config
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  vars:
    state: BACKUP
    priority: 90
  when: inventory_hostname == "ngx2"

- name: custom error page
  copy:
    src: servicedown.html
    dest: /usr/share/nginx/html/

- name: start services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - nginx
    - keepalived

- name: include tasks for node_exporter
  include_role:
    name: common
    tasks_from: node_exporter.yml
