# -*- mode: ruby -*-
# vim: set ft=ruby :

$script = <<-SCRIPT
mkdir -p ~root/.ssh
cp ~vagrant/.ssh/auth* ~root/.ssh
yum install -y mdadm smartmontools hdparm gdisk
# create raid-6 on 5 disks
mdadm --zero-superblock --force /dev/sd{b,c,d,e,f,g,h}
mdadm --create --verbose /dev/md0 -l 6 -n 5 /dev/sd{b,c,d,e,f}
# add 2 spare disks
mdadm /dev/md0 --add /dev/sdg /dev/sdh
# create fs and mount point
mkfs.ext4 /dev/md0
mkdir /raid
echo "/dev/md0 /raid ext4 defaults 0 0" >> /etc/fstab
mount -a
# set 777 for user access
chmod 777 /raid
# create mdadm.conf
echo "DEVICE partitions" > /etc/mdadm.conf
mdadm --detail --scan --verbose | awk '/ARRAY/ {print}' >> /etc/mdadm.conf
SCRIPT

MACHINES = {
  :myotuslinux => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.101',
    :disks => {
      :sata1 => {
        :dfile => './sata1.vdi',
        :size => 250,
        :port => 1
      },
      :sata2 => {
        :dfile => './sata2.vdi',
        :size => 250,
        :port => 2
      },
      :sata3 => {
        :dfile => './sata3.vdi',
        :size => 250,
        :port => 3
      },
      :sata4 => {
        :dfile => './sata4.vdi',
        :size => 250,
        :port => 4
      },
      :sata5 => {
        :dfile => './sata5.vdi',
        :size => 250,
        :port => 5
      },
      :sata6 => {
        :dfile => './sata6.vdi',
        :size => 250,
        :port => 6
      },
      :sata7 => {
      :dfile => './sata7.vdi',
      :size => 250,
      :port => 7
      }
    }
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s

      #box.vbguest.auto_update = false
      box.vm.box_check_update = false
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      
      box.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        needsController = false

        boxconfig[:disks].each do |dname, dconf|
          unless File.exist?(dconf[:dfile])
            vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
            needsController = true
          end

        end
      if needsController == true
        vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
        boxconfig[:disks].each do |dname, dconf|
          vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
        end
    end
  end
  box.vm.provision "shell", inline: $script
end
end
end
