---
# tasks file for roles/proxysql

- name: install percona repo
  yum:
    name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    state: present

- name: configure percona repo for pxc-80
  shell: |
    percona-release enable-only pxc-80 release
    percona-release enable tools release

- name: install packages
  yum:
    name:
      - percona-xtradb-cluster-client
      - proxysql2
      - keepalived
      #- psmisc # killall for keepalived
      #- /usr/bin/audit2allow
    state: present
    
- name: update selinux policies
  yum:
    name:
      - selinux-policy
      - selinux-policy-targeted
    state: latest

- name: configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  vars:
    state: MASTER
    priority: 100
  when: inventory_hostname == "sqlp1"

- name: configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  vars:
    state: BACKUP
    priority: 90
  when: inventory_hostname == "sqlp2"

- name: start proxysql
  systemd: name=proxysql.service state=started enabled=yes

- name: start keepalived
  systemd: name=keepalived state=restarted enabled=yes

  #groupadd -r keepalived_script
  #useradd -r -s /sbin/nologin -g keepalived_script -M keepalived_script

- name: connect proxysql to percona cluster
  shell: mysql -u admin -padmin -h 127.0.0.1 -P 6032 -NBe "{{ item }}"
  with_items:
    - "INSERT INTO mysql_servers(hostgroup_id, hostname, port) VALUES (0,'192.168.100.101',3306);"
    - "INSERT INTO mysql_servers(hostgroup_id, hostname, port) VALUES (0,'192.168.100.102',3306);"
    - "INSERT INTO mysql_servers(hostgroup_id, hostname, port) VALUES (0,'192.168.100.103',3306);"

    - "UPDATE global_variables SET variable_value='proxysql' WHERE variable_name='mysql-monitor_username';"
    - "UPDATE global_variables SET variable_value='kdDL168tyugc' WHERE variable_name='mysql-monitor_password';"

    - "INSERT INTO mysql_users (username,password) VALUES ('sbuser','{{ sbuser_password }}');"
    - "INSERT INTO mysql_users(username, password, default_hostgroup) VALUES ('mmuser','{{ mmuser_password }}',0);"

    - "LOAD MYSQL VARIABLES TO RUNTIME;"
    - "SAVE MYSQL VARIABLES TO DISK;"
    - "LOAD MYSQL SERVERS TO RUNTIME;"
    - "SAVE MYSQL SERVERS TO DISK;"
    - "LOAD MYSQL USERS TO RUNTIME;"
    - "SAVE MYSQL USERS TO DISK;"
