Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "log" do |log|
    log.vm.box = "centos/7"
    log.vm.hostname = "log"
    log.vm.network "private_network", ip: "192.168.33.20"
    log.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
      vb.name = "log"
    end
    log.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible.yml"
      ansible.tags = "epel-package, systemd-journal-gateway, lnav"
    end
    log.vm.provision "ansible", playbook: "ansible.yml", tags: "cfg-log"
    #log.vm.provision "shell", inline: "shutdown -r now"
  end

  config.vm.define "web" do |web|
    web.vm.box = "centos/7"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.33.10"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
      vb.name = "web"
    end
    web.vm.provision "ansible", playbook: "ansible.yml", tags: "epel-package, cfg-pre-elk"
    web.vm.provision "ansible", playbook: "ansible.yml", tags: "systemd-journal-gateway, lnav, nginx, audispd-plugins, filebeat"
    web.vm.provision "ansible", playbook: "ansible.yml", tags: "cfg-web"
    web.vm.provision "ansible", playbook: "ansible.yml", tags: "filebeat-conf"
    web.vm.provision "shell", inline: "shutdown -r now"
  end

  config.vm.define "elk" do |elk|
    elk.vm.box = "centos/7"
    elk.vm.hostname = "elk"
    elk.vm.network "private_network", ip: "192.168.33.30"
    elk.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
      vb.name = "elk"
    end
    elk.vm.provision "ansible", playbook: "ansible.yml", tags: "cfg-pre-elk"
    elk.vm.provision "ansible", playbook: "ansible.yml", tags: "install-elk"
    elk.vm.provision "ansible", playbook: "ansible.yml", tags: "elk-conf"
    elk.vm.provision "ansible", playbook: "ansible.yml", tags: "cfg-post-elk"
  end

end
