version: "3"
services:
  nginx:
    image: mynginx
    ports:
      - 1234:80
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
      - ./nginx/www:/var/www
    links:
      - myphp
  myphp:
    image: myphp
    volumes:
      - ./nginx/www:/var/www


