# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "qpbdqp/rpmrepo"
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
