# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.define "server" do |server|
      server.vm.hostname = "server"
      server.vm.network "private_network", ip: "192.168.20.10"
      server.vm.provision "ansible", playbook: "ansible.yml"
  end
  config.vm.define "backup" do |backup|
      backup.vm.hostname = "backup"
      backup.vm.network "private_network", ip: "192.168.20.20"
      backup.vm.provision "ansible", playbook: "ansible.yml"
  end
end
