- name: create database, user and grant privileges for mattermost
  shell: mysql -u root --password="{{ mysql_root_password }}" -NBe "{{ item }}"
  with_items:
    - "create user 'mmuser'@'%' identified by '{{ mmuser_password }}';"
    - "create database mattermost;"
    - "grant all privileges on mattermost.* to 'mmuser'@'%';"
  when: inventory_hostname == "pxc1"

- name: create user and grant privileges for proxysql
  shell: mysql -u root --password="{{ mysql_root_password }}" -NBe "{{ item }}"
  with_items:
    - "CREATE USER 'proxysql'@'%' IDENTIFIED WITH mysql_native_password by '{{ proxysql_password }}';"
    - "GRANT USAGE ON *.* TO 'proxysql'@'%';"
    - "CREATE USER 'sbuser'@'192.168.100.104' IDENTIFIED BY '{{ sbuser_password }}';"
    - "CREATE USER 'sbuser'@'192.168.100.105' IDENTIFIED BY '{{ sbuser_password }}';"
    - "GRANT ALL ON *.* TO 'sbuser'@'192.168.100.104', 'sbuser'@'192.168.100.105';"
  when: inventory_hostname == "pxc1"
