---
- name: postfix + dovecot
  hosts: all
  remote_user: vagrant
  become: true
  gather_facts: no

  tasks:
    - name: remove sendmail
      yum:
        name: sendmail
        state: absent
    - name: install dovecot
      yum:
        name: dovecot
        state: present
    - name: install telnet
      yum:
        name: telnet
        state: present
    - name: install mc
      yum:
        name: mc
        state: present
    - name: set hostname
      command: hostnamectl set-hostname mail.local.lan
    - name: edit postfix/main.cf
      blockinfile:
        path: /etc/postfix/main.cf
        block: |
          myhostname = mail.local.lan
          mydomain = local.lan
          myorigin = $mydomain
          inet_interfaces = all
          mydestination = $myhostname, localhost.$mydomain, localhost, $mydomain
          mynetworks = 192.168.33.0/24, 127.0.0.0/8
          relay_domains =
          home_mailbox = Maildir/
          # virtual mailboxes
          virtual_mailbox_domains = example.com
          virtual_mailbox_base = /var/mail/vhosts
          virtual_mailbox_maps = hash:/etc/postfix/vmailbox
          virtual_minimum_uid = 1000
          virtual_uid_maps = static:5000
          virtual_gid_maps = static:5000
    - name: edit /etc/postfix/vmailbox
      blockinfile:
        path: /etc/postfix/vmailbox
        block: |
          user3@example.com   example.com/user3/
          user4@example.com   example.com/user4/
        create: yes
    - name: edit /etc/postfix/master.cf
      blockinfile:
        path: /etc/postfix/master.cf
        block: |
          dovecot unix - n n - - pipe
            flags=DRhu user=vmail:vmail argv=/usr/lib/dovecot/deliver -f ${sender} -d $(recipient)
    - name: create users
      shell: |
        adduser user1
        adduser user2
        echo user1:test | chpasswd
        echo user2:test | chpasswd
        mkdir /home/user1/Maildir /home/user2/Maildir
        chown user1:user1 /home/user1/Maildir
        chown user2:user2 /home/user2/Maildir
        chmod -R 775 /home/user1/Maildir
        chmod -R 775 /home/user2/Maildir
        #
        groupadd -g 5000 vmail
        useradd -u 5000 -g vmail -s /sbin/nologin -d /home/vmail -m vmail
        usermod -aG vmail postfix
        usermod -aG vmail dovecot
        mkdir -p /var/mail/vhosts/example.com
        chown -R vmail:vmail /var/mail/vhosts
        chmod -R 775 /var/mail/vhosts
        postmap /etc/postfix/vmailbox
    - name: create dovecot users
      blockinfile:
        path: /etc/dovecot/passwd
        block: |
          user3@example.com:{PLAIN}test
          user4@example.com:{PLAIN}test
        create: yes
    - name: edit dovecot.conf
      blockinfile:
        path: /etc/dovecot/dovecot.conf
        block: |
          protocols = imap pop3

          # It's nice to have separate log files for Dovecot. You could do this
          # by changing syslog configuration also, but this is easier.
          log_path = /var/log/dovecot.log
          info_log_path = /var/log/dovecot-info.log

          # Disable SSL for now.
          ssl = no
          disable_plaintext_auth = no

          # We're using Maildir format
          #mail_location = maildir:~/Maildir

          # postfix puts mail here
          mail_location = maildir:~/

          # If you're using POP3, you'll need this:
          pop3_uidl_format = %g

          # Authentication configuration:
          auth_verbose = yes
          auth_mechanisms = plain
          passdb {
            driver = passwd-file
            args = /etc/dovecot/passwd
          }
          userdb {
            driver = static
            args = uid=vmail gid=vmail home=/var/mail/vhosts/%d/%n
          }
    - name: restart dovecot
      systemd:
        name: dovecot.service
        state: restarted
    - name: restart postfix
      systemd:
        name: postfix.service
        state: restarted
