---
- name: postfix + dovecot
  hosts: all
  remote_user: vagrant
  become: true
  gather_facts: no

  tasks:
    - name: remove sendmail
      yum:
        name: sendmail
        state: absent
    - name: install dovecot
      yum:
        name: dovecot
        state: present
    - name: install telnet
      yum:
        name: telnet
        state: present
    - name: install mc
      yum:
        name: mc
        state: present
    - name: set hostname
      command: hostnamectl set-hostname mail.local.lan
    - name: edit postfix/main.cf
      blockinfile:
        path: /etc/postfix/main.cf
        block: |
          myhostname = mail.local.lan
          mydomain = local.lan
          myorigin = $mydomain
          inet_interfaces = all
          mydestination = $myhostname, localhost.$mydomain, localhost, $mydomain
          mynetworks = 192.168.33.0/24, 127.0.0.0/8
          relay_domains =
          home_mailbox = Maildir/
    - name: edit /etc/postfix/master.cf
      blockinfile:
        path: /etc/postfix/master.cf
        block: |
          dovecot unix - n n - - pipe
            flags=DRhu user=vmail:vmail argv=/usr/lib/dovecot/deliver -f ${sender} -d $(recipient)
    - name: edit /etc/dovecot/dovecot.conf
      blockinfile:
        path: /etc/dovecot/dovecot.conf
        block: |
          protocols = pop3 pop3s
          mail_location = maildir:~/Maildir
    - name: create users
      shell: |
        adduser user1
        adduser user2
        echo user1:test | chpasswd
        echo user2:test | chpasswd
        mkdir /home/user1/Maildir /home/user2/Maildir
        chown user1:user1 /home/user1/Maildir
        chown user2:user2 /home/user2/Maildir
        chmod -R 777 /home/user1/Maildir
        chmod -R 777 /home/user2/Maildir
    - name: restart dovecot
      systemd:
        name: dovecot.service
        state: restarted
    - name: restart postfix
      systemd:
        name: postfix.service
        state: restarted
