# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.define "mail" do |mail|
      mail.vm.hostname = "mail"
      mail.vm.network "private_network", ip: "192.168.33.10"
      mail.vm.provision "ansible", playbook: "ansible.yml"
  end
end
