- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: install borg
  yum:
    name: borgbackup
    state: present

- name: copy ssh pub key
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', 'id_rsa.pub') }}"
