---
- name: routing fix selected
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: set default gw to 192.168.100.10
      shell: |
        echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
        echo "GATEWAY=192.168.100.10" >> /etc/sysconfig/network-scripts/ifcfg-eth1
        service network restart
